# 现货交易版本配置
strategy:
  signal_generation:
    sentiment_threshold_buy: 0.05      # 买入阈值
    sentiment_threshold_sell: -0.05    # 卖出阈值（仅平仓，不做空）
    max_positions: 1
    news_lookback_minutes: 10
    signal_decay_minutes: 5
    holding_period: 30
    
  risk_management:
    max_holding_minutes: 1440          # 24小时（现货可以长期持有）
    stop_loss: 0.05                    # 5%止损
    take_profit: 0.10                  # 10%止盈
    max_drawdown: 0.10
    intraday_loss_limit: 0.05
    consecutive_loss_limit: 5
    
  position_sizing:
    method: fixed
    fixed_size: 0.95                   # 95%仓位
    leverage: 1.0                      # 无杠杆
    
  trading_mode: "spot"                 # 现货模式（只做多，不做空）

# 其他配置保持不变...
evaluation:
  backtest:
    start_date: '2025-05-22'
    end_date: '2025-07-08'
    initial_capital: 100000
    transaction_cost: 0.001
    slippage: 0.0005
    rebalance_freq: 1min
    min_holding_minutes: 5
    max_trades_per_day: 50 